=== artas360/flowsim/config/Flowsim_config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Flowsim (Topology,Events?,Simulation?)>
<!ATTLIST Flowsim
	version CDATA #REQUIRED
	datetime CDATA #IMPLIED
>
<!ELEMENT Simulation (Stop_condition)>
<!ELEMENT Stop_condition (#PCDATA)>
<!ATTLIST Stop_condition
	condition_type CDATA #REQUIRED
	condition_value CDATA #REQUIRED
>
<!ELEMENT Events (Event+)>
<!ELEMENT Event (#PCDATA)>
<!ATTLIST Event
	type CDATA #REQUIRED
	event_target IDREF #IMPLIED
	trigger_type CDATA #REQUIRED
	trigger_value CDATA #REQUIRED
>
<!ELEMENT Topology (Nodes, Links)>
<!ELEMENT Nodes (Default?, Node+)>
<!ELEMENT Default (#PCDATA)>
<!ATTLIST Default
	name CDATA #REQUIRED
>
<!ELEMENT Node (#PCDATA)>
<!ATTLIST Node
	id ID #REQUIRED
	name CDATA #IMPLIED
	arrival_rate CDATA #REQUIRED
	service_rate CDATA #REQUIRED
>
<!ELEMENT Links (Default?, Link+)>
<!ELEMENT Default (#PCDATA)>
<!ATTLIST Default
	weight CDATA #REQUIRED
	capacity CDATA #REQUIRED 
	unidirectional (False | True) "True"
>
<!ELEMENT Link (#PCDATA)>
<!ATTLIST Link
	source_id IDREF #REQUIRED
	destination_id IDREF #REQUIRED
	weight CDATA "1"
	capacity CDATA "1"
	unidirectional (False | True) "True"
>
<!ELEMENT Link (#PCDATA)>
<!ATTLIST Link
	source_id IDREF #REQUIRED
	destination_id IDREF #REQUIRED
	weight CDATA "1"
	capacity CDATA "1"
	unidirectional (False | True) "True"
>

=== artas360/flowsim/config/config-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Flowsim SYSTEM "Flowsim_config.dtd">
<Flowsim datetime="2014-04-15 10:09" version="develop">
	<Simulation>
		<Convergence number_samples="10" epsilon="1e-3" check_interval="1e3"/>
	</Simulation>
	<Events>
		<Event type="arrival_burst_event" event_target="1" trigger_type="time" trigger_value="3000" effect_value=".9"/>
        <Event type="sample_event" event_target="None" trigger_type="time" trigger_value="0." effect_value="15"/>
        <Event type="reconfigure_topology_event" event_target="None" trigger_type="time" trigger_value="0." effect_value="3001"/>
        <!--watcher_event will keep the simulation running until trigger-->
		<Event type="watcher_event" event_target="None" trigger_type="time" trigger_value="5000" effect_value="0"/>
	</Events>
	<Topology>
        <Ghost enabled="True"/>
		<Nodes>
			<Default name="" rx_slot="1" tx_slot="1"/>
			<Node id="0" name="node85" arrival_rate=".3" service_rate=".4" rx_slot="1" tx_slot="1"/>
			<Node id="1" name="node86" arrival_rate=".3" service_rate=".4"/>
		</Nodes>
		<Links>
			<Default weight="1." capacity="1" unidirectional="True"/>
			<Link source_id="0" destination_id="1" weight="1" capacity="1" unidirectional="True" enabled="True"/>
			<Link source_id="1" destination_id="0" weight="1" capacity="2" unidirectional="True" enabled="True"/>
		</Links>
	</Topology>
</Flowsim>

=== artas360/flowsim/config/config-2-nodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Flowsim SYSTEM "Flowsim_config.dtd">
<Flowsim datetime="2014-04-15 10:09" version="develop">
	<Simulation>
		<Stop_condition condition_type="time" condition_value="1500"/>
		<!--Stop_condition condition_type="convergence" condition_value="blocking_rate"/-->
	</Simulation>
	<Events>
		<Event type="arrival_burst_event" event_target="0" trigger_type="time" trigger_value="130000" effect_value=".9"/>
		<Event type="arrival_burst_event" event_target="1" trigger_type="time" trigger_value="130000" effect_value=".9"/>
		<Event type="sample_event" event_target="Blocking_rate" trigger_type="time" trigger_value="0." effect_value="15"/>
	</Events>
	<Topology>
		<Nodes>
			<Default name=""/>
			<Node id="0" name="node0" arrival_rate=".1" service_rate=".9"/>
			<Node id="1" name="node1" arrival_rate=".1" service_rate=".9"/>
		</Nodes>
		<Links>
			<Default weight="1." capacity="1" unidirectional="True"/>
			<Link source_id="0" destination_id="1" weight="1" capacity="1" unidirectional="False"/>
			<Link source_id="1" destination_id="0" weight="1" capacity="1" unidirectional="False"/>
		</Links>
	</Topology>
</Flowsim>

=== artas360/flowsim/config/config-meshed-5-nodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Flowsim SYSTEM "Flowsim_config.dtd">
<Flowsim datetime="2014-04-15 10:09" version="develop">
	<Simulation>
		<Convergence number_samples="10" epsilon="1e-4" check_interval="1e3"/>
	</Simulation>
	<Events>
		<Event type="arrival_burst_event" event_target="0" trigger_type="time" trigger_value="19000" effect_value=".9"/>
		<Event type="arrival_burst_event" event_target="1" trigger_type="time" trigger_value="19000" effect_value=".9"/>
		<Event type="arrival_burst_event" event_target="4" trigger_type="time" trigger_value="19000" effect_value=".9"/>
		<Event type="watcher_event" event_target="None" trigger_type="time" trigger_value="20000" effect_value="0"/>
		<Event type="sample_event" event_target="0" trigger_type="time" trigger_value="0." effect_value="10"/>
	</Events>
	<Topology>
        <Ghost enabled="False"/>
		<Nodes>
			<Default name="" rx_slot="3" tx_slot="2"/>
			<Node id="0" name="node0" arrival_rate=".1" service_rate=".9"/>
			<Node id="1" name="node1" arrival_rate=".1" service_rate=".9" rx_slot="3" tx_slot="3"/>
			<Node id="2" name="node2" arrival_rate=".1" service_rate=".9"/>
			<Node id="3" name="node3" arrival_rate=".1" service_rate=".9" rx_slot="3" tx_slot="3"/>
			<Node id="4" name="node4" arrival_rate=".1" service_rate=".9"/>
		</Nodes>
		<Links>
			<Default weight="1." capacity="1" unidirectional="True"/>
			<Link source_id="0" destination_id="1" weight="1" capacity="1" unidirectional="False"/>
			<Link source_id="0" destination_id="3" weight="1" capacity="1" unidirectional="False"/>
			<Link source_id="3" destination_id="4" weight="1" capacity="1" unidirectional="False"/>
			<Link source_id="3" destination_id="2" weight="1" capacity="1" unidirectional="False"/>
			<Link source_id="1" destination_id="2" weight="1" capacity="1" unidirectional="False"/>
			<Link source_id="1" destination_id="4" weight="1" capacity="1" unidirectional="False"/>
		</Links>
	</Topology>
</Flowsim>
